-- 0007_subscription_plans | Phase 1 | spec 3.1
CREATE TABLE subscription_plans (
  id                              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  code                            text        UNIQUE NOT NULL CHECK (length(trim(code)) > 0),
  name                            text        NOT NULL CHECK (length(trim(name)) > 0),
  status                          text        NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
  max_active_events               integer     CHECK (max_active_events IS NULL OR max_active_events >= 0),
  max_users                       integer     CHECK (max_users IS NULL OR max_users >= 0),
  max_storage_gb                  integer     CHECK (max_storage_gb IS NULL OR max_storage_gb >= 0),
  max_guests_per_event            integer     CHECK (max_guests_per_event IS NULL OR max_guests_per_event >= 0),
  max_concurrent_sessions         integer     NOT NULL DEFAULT 5 CHECK (max_concurrent_sessions >= 0),
  max_emails_per_month            integer     CHECK (max_emails_per_month IS NULL OR max_emails_per_month >= 0),
  max_api_requests_per_month      integer     CHECK (max_api_requests_per_month IS NULL OR max_api_requests_per_month >= 0),
  max_outgoing_webhooks           integer     CHECK (max_outgoing_webhooks IS NULL OR max_outgoing_webhooks >= 0),
  max_custom_event_types          integer     CHECK (max_custom_event_types IS NULL OR max_custom_event_types >= 0),
  audit_log_retention_days        integer     CHECK (audit_log_retention_days IS NULL OR audit_log_retention_days >= 0),
  trial_pool_sms_per_month        integer     CHECK (trial_pool_sms_per_month IS NULL OR trial_pool_sms_per_month >= 0),
  includes_conference_module      boolean     NOT NULL DEFAULT FALSE,
  includes_branded_exports        boolean     NOT NULL DEFAULT FALSE,
  includes_multi_currency         boolean     NOT NULL DEFAULT FALSE,
  includes_cross_event_analytics  boolean     NOT NULL DEFAULT FALSE,
  includes_white_label            boolean     NOT NULL DEFAULT FALSE,
  includes_custom_domain          boolean     NOT NULL DEFAULT FALSE,
  includes_ai_vendor_recommender  boolean     NOT NULL DEFAULT FALSE,
  includes_ai_command_center      boolean     NOT NULL DEFAULT FALSE,
  includes_vendor_payouts         boolean     NOT NULL DEFAULT FALSE,
  includes_byo_email              boolean     NOT NULL DEFAULT FALSE,
  includes_sso                    boolean     NOT NULL DEFAULT FALSE,
  includes_api_full               boolean     NOT NULL DEFAULT FALSE,
  includes_cloud_offload          boolean     NOT NULL DEFAULT FALSE,
  includes_esignature             boolean     NOT NULL DEFAULT FALSE,
  includes_po_billing             boolean     NOT NULL DEFAULT FALSE,
  includes_net30_terms            boolean     NOT NULL DEFAULT FALSE,
  sla_uptime_percent              numeric(5,2) CHECK (sla_uptime_percent IS NULL OR (sla_uptime_percent BETWEEN 0 AND 100)),
  price_inr_monthly               numeric(10,2) CHECK (price_inr_monthly IS NULL OR price_inr_monthly >= 0),
  price_inr_yearly                numeric(10,2) CHECK (price_inr_yearly  IS NULL OR price_inr_yearly  >= 0),
  price_usd_monthly               numeric(10,2) CHECK (price_usd_monthly IS NULL OR price_usd_monthly >= 0),
  price_usd_yearly                numeric(10,2) CHECK (price_usd_yearly  IS NULL OR price_usd_yearly  >= 0),
  setup_fee_inr                   numeric(10,2) NOT NULL DEFAULT 0 CHECK (setup_fee_inr >= 0),
  setup_fee_usd                   numeric(10,2) NOT NULL DEFAULT 0 CHECK (setup_fee_usd >= 0),
  trial_days                      integer     NOT NULL DEFAULT 0 CHECK (trial_days >= 0),
  created_at                      timestamptz NOT NULL DEFAULT now(),
  archived_at                     timestamptz,
  CHECK (status <> 'archived' OR archived_at IS NOT NULL)
);
CREATE INDEX idx_subscription_plans_status ON subscription_plans (status) WHERE status = 'active';
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans FORCE ROW LEVEL SECURITY;
