-- Phase 12 Unit 110c: 10 system event_templates per spec Part 34.0.
INSERT INTO event_templates (tenant_id, code, name, description, event_type_id, scaffold, is_system, is_published, use_count) VALUES
  (NULL, 'tmpl-wedding-classic',           'Classic Wedding',           'Standard 2-day wedding with mehendi, sangeet, ceremony',                  (SELECT id FROM event_types WHERE code='wedding'),                '{"phases":["pre","day","post"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-wedding-destination',       'Destination Wedding',       '4-day destination wedding with travel logistics',                         (SELECT id FROM event_types WHERE code='wedding'),                '{"phases":["pre","arrival","day","post"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-engagement-intimate',       'Intimate Engagement',       'Single-day engagement with close family + friends',                       (SELECT id FROM event_types WHERE code='engagement'),             '{"phases":["pre","day"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-corporate-conference-1day', '1-day Corporate Conference', 'Single-track conference with sessions, networking, sponsors',            (SELECT id FROM event_types WHERE code='corporate-conference'),   '{"phases":["pre","day"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-corporate-conference-3day', '3-day Corporate Conference', 'Multi-track conference with workshops, keynotes, expo',                  (SELECT id FROM event_types WHERE code='corporate-conference'),   '{"phases":["pre","day1","day2","day3","post"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-product-launch-press',      'Product Launch (Press)',    'Product launch event with press, demos, livestream',                     (SELECT id FROM event_types WHERE code='product-launch'),         '{"phases":["pre","day","post"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-fundraiser-gala-blacktie',  'Black-tie Fundraiser Gala', 'Formal gala with auction, dinner, performances',                         (SELECT id FROM event_types WHERE code='fundraiser-gala'),        '{"phases":["pre","day","post"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-workshop-bootcamp-weekend', 'Weekend Bootcamp',          '2-day intensive learning bootcamp',                                       (SELECT id FROM event_types WHERE code='workshop-bootcamp'),      '{"phases":["pre","day1","day2"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-birthday-milestone',        'Milestone Birthday',        'Themed milestone birthday party with entertainment',                      (SELECT id FROM event_types WHERE code='birthday'),               '{"phases":["pre","day"]}'::jsonb, TRUE, TRUE, 0),
  (NULL, 'tmpl-concert-music-festival',    'Music Festival',            'Multi-stage outdoor music festival with vendors + camping',              (SELECT id FROM event_types WHERE code='concert-music-festival'), '{"phases":["pre","day1","day2","post"]}'::jsonb, TRUE, TRUE, 0)
ON CONFLICT DO NOTHING;
